config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => 'accounts', path_names: {sign_in: "login", sign_out: "logout"}
  root to: "sales#index"

  resources :users
  resources :sales do
  	put :favorite, on: :member
  	resources :photos
  	collection do
  		get 'search'
      get 'favorites'
      get 'current_user_sales'
  	end
  end
end

app/models/favorite_sale.rb
class FavoriteSale < ActiveRecord::Base
  belongs_to :sale
  belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  extend Dragonfly::Model
  belongs_to :sale
  dragonfly_accessor :image
 
  validates :image, presence: true
  validates_size_of :image, maximum: 3000.kilobytes,
                    message: "should be no more than 500 KB", if: :image_changed?
 
  validates_property :format, of: :image, in: [:jpeg, :jpg, :png, :bmp], case_sensitive: false,
                     message: "should be either .jpeg, .jpg, .png, .bmp", if: :image_changed?
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode
  belongs_to :user
  has_many :photos, :dependent => :destroy
  has_many :favorite_sales
  has_many :favorited_by, :through => :favorite_sales, :source => :user

  def format_time
    unless self.start_time == nil || self.end_time == nil
      start_time = self.start_time.to_s.split(" ")[1].slice(0..4)
      end_time = self.end_time.to_s.split(" ")[1].slice(0..4)
      time = "from " + start_time + " to " + end_time
    end
  end

  def format_date
    unless self.start_date == nil || self.end_date == nil
      start_date = self.start_date.to_s.split("-")
      end_date = self.end_date.to_s.split("-")
      formatted_start_date = start_date[1].to_s + "/" + start_date[2].to_s + "/" + start_date[0].to_s.slice(2..4)
      formatted_end_date = end_date[1].to_s + "/" + end_date[2].to_s + "/" + end_date[0].to_s.slice(2..4)
      formatted_start_date + " - " + formatted_end_date
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :username

  has_many :sales, :dependent => :destroy
  has_many :favorite_sales
  has_many :favorites, :through => :favorite_sales, :source => :sale
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :email
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def new
    @sale = Sale.find(params[:sale_id])
    @photo = @sale.photos.new
    @photos = @sale.photos.order('created_at DESC')
  end

  def create
    @sale = Sale.find(params[:sale_id])
    @photo = @sale.photos.new(photo_params)
    if @photo.save
      respond_to do |format|
        format.html { redirect_to root_path, notice: "New sale was added." }
        format.js
      end
    end
  end

  def destroy
    @sale = Sale.find(params[:sale_id])
    @photo = @sale.photos.find(params[:id])
    @photo.destroy
    respond_to do |format|
      format.html
      format.js
    end
  end

private

  def photo_params
    params.require(:photo).permit(:image, :sale_id)
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  layout "main", only: [:index]

  def index
    @sales = Sale.all
  end

  def new
    @sale = Sale.new
    @sale.photos.build
  end

  def create
    @sale = Sale.new(sale_params)
    @sale.user_id = current_user.id
    if @sale.save
      respond_to do |format|
        format.html { redirect_to new_sale_photo_path(@sale) }
        format.js
      end
    else
      'new'
    end
  end

  def show
    @sale = Sale.find(params[:id])
    @hash = Gmaps4rails.build_markers(@sale) do |sale, marker|
      marker.lat sale.latitude
      marker.lng sale.longitude
      marker.picture({
        "url" => view_context.image_path('google_map_icon.png'),
        "width" => 64,
        "height" => 64
      })
    end
  end

  def edit
    @sale = Sale.find(params[:id])
  end

  def update
    @sale = Sale.find(params[:id])
    @photos = @sale.photos
    if @sale.update(sale_params)
      flash[:notice] = "Your sale updated successfully!"
      redirect_to user_path
    else
      render edit_sale_path
    end
  end

  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to user_path}
      format.js
    end
  end

  def favorite
    @sale = Sale.find(params[:id])
    type = params[:type]
    if type == "favorite"
      current_user.favorites << @sale
      redirect_to :back, notice: "You favorited #{@sale.title}"
    elsif type == "unfavorite"
      current_user.favorites.delete(@sale)
      redirect_to :back, notice: "Unfavorited #{@sale.title}"
    else
      redirect_to :back, notice: 'Nothing happened.'
    end
  end

  def favorites
    @favorites = current_user.favorites
  end

  def current_user_sales
    @current_user_sales = current_user.sales
  end

  def search
    if params[:address].present?
      @sales = Sale.near(params[:address])
    else
      @sales = Sale.all
    end
    @hash = Gmaps4rails.build_markers(@sales) do |sale, marker|
      marker.lat sale.latitude
      marker.lng sale.longitude
      marker.infowindow render_to_string(:partial => "/sales/infowindow", :locals =>{ :sale => sale })
      marker.picture({
        "url" => view_context.image_path('google_map_icon.png'),
        "width" => 64,
        "height" => 64
      })
    end
  end

private

  def sale_params
    params.require(:sale).permit(:address, :title, :description, :start_date, :end_date, :start_time, :end_time, :user_id, :latitude, :longitude)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @sale = @users.sales
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      'new'
    end
  end

  def show
    @user = current_user
    @sales = @user.sales
  end

private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :remember_me, :username)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
  def glyph(*names)
    content_tag :i, nil, :class => names.map{|name| "glyphicon glyphicon-#{name.to_s.gsub('_','-')}" }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="all">
<head>
  <title>Gigisale</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <style><%= yield :stylesheets %></style>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Istok+Web:700' rel='stylesheet' type='text/css'>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="all">
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="row">
          <%= link_to "GGSALE", root_path, id: "logo-all" %>
        <div class="col-xs-12 col-sm-6 col-md-7 col-lg-4" id="all-search-wrapper">
          <%= form_tag search_sales_path, class: "navbar-form", role: "search", method: :get do %>
            <div class="input-group">
              <%= text_field_tag :address, params[:address], class: "form-control", placeholder: "Where are you looking for?", id: "all-search" %>
              <div class="input-group-btn">
                <%= submit_tag "Search", class: "btn", id: "all-search-btn", 'data-no-turbolink' => true %>
              </div>
            </div>
          <% end %>
        </div>
        <% if user_signed_in? %>
          <button type="button" class="navbar-toggle main-toggle-absolute" id="main-toggle-nav" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar main-toggle-span"></span>
            <span class="icon-bar main-toggle-span"></span>
            <span class="icon-bar main-toggle-span"></span>
          </button>
          <div class="col-xs-12 col-sm-3 col-md-3" id="dropdown-list">
            <div class="collapse navbar-collapse">
              <ul class="nav navbar-nav navbar-right" id="dropdown-list">
                <li class="dropdown" id="all-dropdown-link">
                  <a data-toggle="dropdown" data-target="#"><b id="all-glyph" class="glyphicon glyphicon-user"></b><span id="all-user-name"><%= current_user.username %></span><b class="caret" id="all-caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Add Sale", new_sale_path, id: "new_sale", class: "btn  btn-dropdown", remote: true %></li>
                    <li><%= link_to "Manage Sales", user_path(current_user), id: "user_sales", class: "btn btn-dropdown" %></li>
                    <li><%= link_to 'Edit profile', edit_user_registration_path, class: "btn btn-dropdown" %></li>
                    <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-dropdown" %></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        <% else %>
          <div class="col-xs-4 col-sm-4 col-md-3" id="guest-links">
            <%= link_to "Sign Up", new_user_registration_path, class: "all-links" %>
            <%= link_to "Log In", new_user_session_path, class: "all-links" %>
          </div>
        <% end %>
      </div>
    </div>
  </nav>
  <div id="wrapper-all-form"></div>
  <% if notice %>
  	<p class="notice alert alert-success" role="alert"><%= notice %></p>
  <% elsif alert %>
  	<p class="alert alert-danger" role="alert"><%= alert %></p>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gigisale</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Istok+Web:700' rel='stylesheet' type='text/css'>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
  <div class="navbar" role="navigation">
    <div class="container-fluid">
      <div class="row">
        <% if user_signed_in? %>
          <%= link_to "GGSALE", root_path, id: "logo" %>
          <button type="button" class="navbar-toggle" id="main-toggle-nav" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar main-toggle-span"></span>
            <span class="icon-bar main-toggle-span"></span>
            <span class="icon-bar main-toggle-span"></span>
          </button>
          <div class="col-xs-12 col-sm-9 col-lg-9" id="dropdown-list">
            <div class="collapse navbar-collapse">
              <ul class="nav navbar-nav navbar-right" id="dropdown-list">
                <li class="dropdown" id="dropdown-link">
                  <a data-toggle="dropdown" data-target="#"><b class="glyphicon glyphicon-user"></b><span id="user-name"><%= current_user.username %></span><b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Add Sale", new_sale_path, id: "new_sale", class: "btn  btn-dropdown", remote: true %></li>
                    <li><%= link_to "Manage Sales", user_path(current_user), id: "user_sales", class: "btn btn-dropdown" %></li>
                    <li><%= link_to 'Edit profile', edit_user_registration_path, class: "btn btn-dropdown" %></li>
                    <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-dropdown" %></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        <% else %>
          <div class="row">
            <div class="col-xs-12">
              <%= link_to "GGSALE", root_path, id: "logo-guest" %>
              <div class="navbar-right session-links">
                <%= link_to "Sign Up", new_user_registration_path, class: "session-link" %>
                <%= link_to "Log In", new_user_session_path, class: "session-link"%>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <%= yield %>
</body>
</html>

app/views/photos/_photo.html.erb
<div class="col-xs-4" id='<%= photo.id %>'>
  <%= link_to image_tag(photo.image.thumb('180x180#').url, class: 'img-thumbnail img-responsive'), photo.image.remote_url, target: '_blank' %>
  <%= link_to glyph(:trash), sale_photo_path(photo.sale, photo), class: 'photo-trash', method: :delete, remote: :true %>
</div>

app/views/photos/create.js.erb
<% if @photo.new_record? %>
  alert('The photo could not be uploaded: <%= j @photo.errors.full_messages.join(', ').html_safe %>');
<% else %>
  $('#photos-list').prepend('<%= j render @photo %>');
<% end %>

app/views/photos/destroy.js.erb
$('#<%=@photo.id%>').remove();

app/views/photos/new.html.erb
<h1 class="text-center add-photo-header">Your photos</h1>
<div class="row">
  <div class="col-xs-12" id="photos-list">
  </div>
</div>
<div id="dropzone" class="fade">Drop pictures here</div>
<%= form_for [@sale,@photo] do |f| %>
  <div class="row">
    <div class="col-xs-offset-3 col-xs-6 col-xs-offset-3 col-sm-offset-4 col-sm-4 col-sm-offset-4" id="upload-wrapper">
      <%= f.file_field :image, id: 'file-field', required: true, multiple: true, name: 'photo[image]'%>
    </div>
  </div>
  <div class="progress-wrapper">
    <p>Bitrate: <span class="bitrate"></span></p>
    <div class="progress">
      <div class="progress-bar" role="progressbar">
        0%
      </div>
    </div>
  </div>
<% end %>
<div class="col-xs-12 text-center">
  <a id="upload-photos" type="button" class="text-center btn button-default" href="<%= sales_path %>">Add photos</a>
</div>

<script>
  $(document).ready(function() {
    var multiple_photos_form = $('#new_photo');
    var wrapper = multiple_photos_form.find('.progress-wrapper');
    var bitrate = wrapper.find('.bitrate');
    var progress_bar = wrapper.find('.progress-bar');

    multiple_photos_form.fileupload({
      dataType: 'script',
      dropZone: $('#dropzone'),
      add: function (e, data) {
        types = /(\.|\/)(gif|jpe?g|png|bmp)$/i;
        file = data.files[0];
        if (types.test(file.type) || types.test(file.name)) {
          data.submit();
        }
        else { alert(file.name + " must be GIF, JPEG, BMP or PNG file"); }
      }
    });

    multiple_photos_form.on('fileuploadstart', function() {
      wrapper.show();
    });

    multiple_photos_form.on('fileuploaddone', function() {
      wrapper.hide();
      progress_bar.width(0);
    });

    multiple_photos_form.on('fileuploadprogressall', function (e, data) {
      bitrate.text((data.bitrate / 1024).toFixed(2) + 'Kb/s');
      var progress = parseInt(data.loaded / data.total * 100, 10);
      progress_bar.css('width', progress + '%').text(progress + '%');
    });

    $(document).bind('dragover', function (e) {
      var dropZone = $('#dropzone'),
              timeout = window.dropZoneTimeout;
      if (!timeout) {
        dropZone.addClass('in');
      } else {
        clearTimeout(timeout);
      }
      var found = false,
              node = e.target;
      do {
        if (node === dropZone[0]) {
          found = true;
          break;
        }
        node = node.parentNode;
      } while (node != null);
      if (found) {
        dropZone.addClass('hover');
      } else {
        dropZone.removeClass('hover');
      }
      window.dropZoneTimeout = setTimeout(function () {
        window.dropZoneTimeout = null;
        dropZone.removeClass('in hover');
      }, 100);
    });
  });
</script>

app/views/sales/_current_user_sales.html.erb
<div class="container-fluid">
  <div class="row">
    <% @current_user_sales.each do |f| %>
      <a href="<%= sale_path(f) %>" data-no-turbolink='true'>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-3 sale-thumb" id="<%= f.id %>">
          <span><%= link_to glyph(:trash), sale_path(f), id: "remove-sale", method: :delete, data: { confirm: "Are you sure?"}, remote: :true %></span>
          <span><%= link_to glyph(:pencil), edit_sale_path(f), id: "update-sale"%></span>
          <% if f.photos.any? %>
            <%= link_to image_tag(f.photos.first.image.thumb('700x500#').url, class: ' sale-photo sale-cover-mobile img-responsive'),
                sale_path(f) %>
            <%= link_to image_tag(f.photos.first.image.thumb('700x500#').url, class: 'sale-photo sale-cover-mobile2'),
                sale_path(f) %>
            <%= link_to image_tag(f.photos.first.image.thumb('1024x600#').url, class: 'sale-cover-tablet'),
                sale_path(f) %>
            <%= link_to image_tag(f.photos.first.image.thumb('358x240#').url, class: 'sale-cover-desktop'),
                sale_path(f) %>
          <% end %>
        </div>
      </a>
    <% end %>
  </div>
</div>

app/views/sales/_favorites_sales.html.erb
<%= render('google_map_script') %>
<%= render('google_map') %>
<div class="container-fluid">
  <div class="row">
    <% @favorites.each do |f| %>
      <a href="<%= sale_path(f) %>" data-no-turbolink='true'>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-3 sale-thumb">
          <span><%= link_to "unfavorite", favorite_sale_path(f, type: "unfavorite"), class: 'icon-unfav', method: :put %></span>
          <% if f.photos.any? %>
            <%= link_to image_tag(f.photos.first.image.thumb('100x80#').url, class: 'sale-cover-mobile'),
                sale_path(f) %>
            <%= link_to image_tag(f.photos.first.image.thumb('170x130#').url, class: 'sale-cover-mobile2'),
                sale_path(f) %>
            <%= link_to image_tag(f.photos.first.image.thumb('270x180#').url, class: 'sale-cover-tablet'),
                sale_path(f) %>
            <%= link_to image_tag(f.photos.first.image.thumb('358x240#').url, class: 'sale-cover-desktop'),
                sale_path(f) %>
          <% end %>
          <p class="text-left title"><%= f.title %></p>
          <p class="text-left address"><%= f.address %></p>
          <p class="text-left date"><%= f.format_date %></p>
        </div>
      </a>
    <% end %>
  </div>
</div>
<%= render('google_map_styles') %>

app/views/sales/_form.html.erb
<div class="container-fluid center_div">
  <%= form_for @sale, :html => {role: "form", class: "form-horizontal", :multipart => true} do |f| %>
    <h2 class="col-sm-offset-3 col-sm-6 text-center">Add a sale</h2>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-6">
        <%= f.label "Address, City, State" %>
        <%= f.text_field :address, autofocus: true, class: "form-control", placeholder: "1234 SW 66th Ave, Portland, OR" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-6">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-6">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control", placeholder: "Description" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-6">
        <%= f.label "Sale start date" %>
        <%= f.date_field :start_date, class: "form-control"%>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-6">
        <%= f.label "Sale end date" %>
        <%= f.date_field :end_date, class: "form-control"%>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-6">
        <%= f.label "Sale start time" %>
        <%= f.time_field :start_time, class: "form-control"%>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-6">
        <%= f.label "Sale end time" %>
        <%= f.time_field :end_time, class: "form-control"%>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-6 text-center">
        <%= f.submit "Continue", class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>

app/views/sales/_google_map.html.erb
<div id="map-wrapper">
  <div id="map"></div>
</div>

app/views/sales/_infowindow.html.erb
<div id="carousel-pictures" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <% sale.photos.each_with_index do |photo, index| %>
      <div class="<% if index == 0 %>item active<% else %>item<% end %>">
        <%= link_to image_tag(photo.image.thumb('180x180#').url, class: 'img-thumbnail'),
            sale_path(sale) %></div>
    <% end %>
  </div>
  <a class="left carousel-control" href="#carousel-pictures" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-pictures" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

app/views/sales/_my_template.html.erb
<a href="/sales/<%= sale.id %>"><div><%= sale.address %></div>
<div><% sale.photos.each do |photo| %></div>
	<div><%= link_to image_tag(photo.image.thumb('180x180#').url, class: 'img-thumbnail'),
      sale_path(sale) %></div></a>
  <% end %>

app/views/sales/_sale.html.erb
<%= form_for sale do |f| %>
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <h3 class="text-center"><%= sale.title %></h3>
      <p class="text-center"><%= sale.format_date %></p>
      <p class="text-center"><%= sale.address %></p>
      <p class="text-center"><%= link_to "View", sale_path(sale), class: "btn btn-primary", role: "button" %></p>
    </div>
  </div>
<% end %>

app/views/sales/create.js.erb
$('#new_sale').remove();
$('#sales').prepend('<%= j render(@sale) %>')

app/views/sales/destroy.js.erb
$('#<%=@sale.id%>').remove();

app/views/sales/edit.html.erb
<%= render("form") %>

app/views/sales/favorites.js.erb
$('#wrapper-all').html('<%= j render("favorites_sales")%>')

app/views/sales/index.html.erb
<video autoplay loop poster="/assets/ggsale-poster.jpg" id="bgvid">
  <source src="/assets/ggsale-intro.webm" type="video/webm" />
  <source src="/assets/ggsale-intro.mp4" type="video/mp4" />
</video>
<div class="row">
  <div class="col-xs-12">
    <h1 id="main-header" class="text-uppercase text-center">Find Your Bargain</h1>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <p class="text-center" id="secondary-header">Buy and sell things effortlessly</p>
  </div>
</div>
<div class="row">
  <div class="col-xs-12" id="search-parent">
    <%= form_tag search_sales_path, class: "form-horizontal", role: "form", method: :get do %>
      <div id="search-wrapper">
        <div class="form-group">
          <%= text_field_tag :address, params[:address], placeholder: "Where are you looking?", class: "form-control", id: "main-search" %>
          <%= submit_tag "Search", class: "btn", id: "main-search-btn", 'data-no-turbolink' => true %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/sales/new.js.erb
$('body').html('<%= j render("form") %>')

app/views/sales/search.html.erb
<%= render('google_map_script') %>
<%= render('google_map') %>
<div class="container-fluid">
  <div class="row">
    <% @sales.each do |sale| %>
      <a href="<%= sale_path(sale) %>" data-no-turbolink='true'>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-3 sale-thumb">
          <% if current_user %>
            <span><%= link_to "unfavorite", favorite_sale_path(sale, type: "unfavorite"), class: 'icon-unfav', method: :put %></span>
            <span><%= link_to glyph(:heart), favorite_sale_path(sale, type: "favorite"), class: 'icon-fav', method: :put %></span>
          <% end %>
          <% if sale.photos.any? %>
            <%= link_to image_tag(sale.photos.first.image.thumb('100x80#').url, class: 'sale-cover-mobile'),
                sale_path(sale) %>
            <%= link_to image_tag(sale.photos.first.image.thumb('170x130#').url, class: 'sale-cover-mobile2'),
                sale_path(sale) %>
            <%= link_to image_tag(sale.photos.first.image.thumb('270x180#').url, class: 'sale-cover-tablet'),
                sale_path(sale) %>
            <%= link_to image_tag(sale.photos.first.image.thumb('358x240#').url, class: 'sale-cover-desktop'),
                sale_path(sale) %>
          <% end %>
          <p class="text-left title"><%= sale.title %></p>
          <p class="text-left address"><%= sale.address %></p>
          <p class="text-left date"><%= sale.format_date %></p>
        </div>
      </a>
    <% end %>
  </div>
</div>
<%= render('google_map_styles') %>

app/views/users/show.html.erb
<div class="row" id="user-menu">
  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-2"><%= link_to "Favorites", favorites_sales_path, id: "favorites_sales", class: "btn", remote: true%></div>
  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-2"><%= link_to "Your sales", current_user_sales_sales_path, id: "current_user_sales", class: "btn", remote: true %></div>
</div>
<div id="wrapper-all"></div>